[2024-05-10T08:50:55.608+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T08:50:55.625+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_push_and_pull_example_dag.pull_from_multiple manual__2024-05-10T08:35:21.620354+00:00 [queued]>
[2024-05-10T08:50:55.630+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_push_and_pull_example_dag.pull_from_multiple manual__2024-05-10T08:35:21.620354+00:00 [queued]>
[2024-05-10T08:50:55.631+0000] {taskinstance.py:2303} INFO - Starting attempt 7 of 7
[2024-05-10T08:50:55.639+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): pull_from_multiple> on 2024-05-10 08:35:21.620354+00:00
[2024-05-10T08:50:55.645+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4657) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T08:50:55.645+0000] {standard_task_runner.py:63} INFO - Started process 4661 to run task
[2024-05-10T08:50:55.645+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xcom_push_and_pull_example_dag', 'pull_from_multiple', 'manual__2024-05-10T08:35:21.620354+00:00', '--job-id', '5823', '--raw', '--subdir', 'DAGS_FOLDER/io_dag.py', '--cfg-path', '/tmp/tmpaipiijxh']
[2024-05-10T08:50:55.646+0000] {standard_task_runner.py:91} INFO - Job 5823: Subtask pull_from_multiple
[2024-05-10T08:50:55.674+0000] {task_command.py:426} INFO - Running <TaskInstance: xcom_push_and_pull_example_dag.pull_from_multiple manual__2024-05-10T08:35:21.620354+00:00 [running]> on host 92f239b8dd4a
[2024-05-10T08:50:55.722+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xcom_push_and_pull_example_dag' AIRFLOW_CTX_TASK_ID='pull_from_multiple' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T08:35:21.620354+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T08:35:21.620354+00:00'
[2024-05-10T08:50:55.723+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T08:50:55.735+0000] {logging_mixin.py:188} INFO - Return
[2024-05-10T08:50:55.737+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T08:50:55.737+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/io_dag.py", line 23, in pull_from_multiple
    push_by_returning_value = values[0]['return_value']
                              ~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-05-10T08:50:55.756+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=xcom_push_and_pull_example_dag, task_id=pull_from_multiple, execution_date=20240510T083521, start_date=20240510T085055, end_date=20240510T085055
[2024-05-10T08:50:55.762+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5823 for task pull_from_multiple (string indices must be integers, not 'str'; 4661)
[2024-05-10T08:50:55.785+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T08:50:55.799+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T08:50:55.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
