[2024-05-17T00:32:56.288+0000] {processor.py:161} INFO - Started process (PID=16517) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T00:32:56.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T00:32:56.290+0000] {logging_mixin.py:188} INFO - [2024-05-17T00:32:56.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T00:32:56.309+0000] {logging_mixin.py:188} INFO - [2024-05-17T00:32:56.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T00:32:56.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T00:32:56.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.038 seconds
[2024-05-17T01:51:08.759+0000] {processor.py:161} INFO - Started process (PID=16572) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T01:51:08.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T01:51:08.760+0000] {logging_mixin.py:188} INFO - [2024-05-17T01:51:08.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T01:51:08.764+0000] {logging_mixin.py:188} INFO - [2024-05-17T01:51:08.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T01:51:08.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T01:51:08.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T02:51:07.669+0000] {processor.py:161} INFO - Started process (PID=16627) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:51:07.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:51:07.671+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:51:07.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:51:07.676+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:51:07.674+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:51:07.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:51:07.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T02:56:12.024+0000] {processor.py:161} INFO - Started process (PID=16691) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:56:12.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:56:12.026+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:56:12.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:56:12.048+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:56:12.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:56:12.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:56:12.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.038 seconds
[2024-05-17T02:56:42.925+0000] {processor.py:161} INFO - Started process (PID=16746) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:56:42.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:56:42.927+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:56:42.926+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:56:42.931+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:56:42.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:56:42.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:56:42.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T02:57:13.757+0000] {processor.py:161} INFO - Started process (PID=16797) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:57:13.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:57:13.758+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:57:13.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:57:13.763+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:57:13.762+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:57:13.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:57:13.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.021 seconds
[2024-05-17T02:57:44.608+0000] {processor.py:161} INFO - Started process (PID=16848) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:57:44.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:57:44.609+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:57:44.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:57:44.614+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:57:44.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:57:44.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:57:44.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T02:58:15.424+0000] {processor.py:161} INFO - Started process (PID=16905) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:58:15.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:58:15.425+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:58:15.425+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:58:15.429+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:58:15.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:58:15.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:58:15.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.018 seconds
[2024-05-17T02:58:46.249+0000] {processor.py:161} INFO - Started process (PID=16956) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:58:46.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:58:46.250+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:58:46.250+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:58:46.255+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:58:46.253+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:58:46.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:58:46.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T02:59:17.083+0000] {processor.py:161} INFO - Started process (PID=17007) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:59:17.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:59:17.085+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:59:17.084+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:59:17.090+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:59:17.089+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:59:17.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:59:17.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T02:59:47.830+0000] {processor.py:161} INFO - Started process (PID=17057) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:59:47.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T02:59:47.832+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:59:47.831+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:59:47.836+0000] {logging_mixin.py:188} INFO - [2024-05-17T02:59:47.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T02:59:47.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T02:59:47.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T03:00:18.641+0000] {processor.py:161} INFO - Started process (PID=17113) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:00:18.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:00:18.642+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:00:18.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:00:18.646+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:00:18.645+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:00:18.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:00:18.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:00:49.419+0000] {processor.py:161} INFO - Started process (PID=17162) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:00:49.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:00:49.420+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:00:49.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:00:49.424+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:00:49.423+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:00:49.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:00:49.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:01:20.311+0000] {processor.py:161} INFO - Started process (PID=17214) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:01:20.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:01:20.312+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:01:20.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:01:20.316+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:01:20.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:01:20.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:01:20.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T03:01:51.130+0000] {processor.py:161} INFO - Started process (PID=17265) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:01:51.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:01:51.131+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:01:51.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:01:51.135+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:01:51.134+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:01:51.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:01:51.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T03:02:21.931+0000] {processor.py:161} INFO - Started process (PID=17322) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:02:21.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:02:21.932+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:02:21.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:02:21.936+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:02:21.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:02:21.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:02:21.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:02:52.809+0000] {processor.py:161} INFO - Started process (PID=17373) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:02:52.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:02:52.810+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:02:52.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:02:52.814+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:02:52.813+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:02:52.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:02:52.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:03:23.637+0000] {processor.py:161} INFO - Started process (PID=17424) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:03:23.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:03:23.638+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:03:23.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:03:23.641+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:03:23.641+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:03:23.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:03:23.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.018 seconds
[2024-05-17T03:03:54.480+0000] {processor.py:161} INFO - Started process (PID=17475) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:03:54.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:03:54.481+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:03:54.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:03:54.485+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:03:54.484+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:03:54.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:03:54.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:04:25.256+0000] {processor.py:161} INFO - Started process (PID=17532) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:04:25.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:04:25.261+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:04:25.261+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:04:25.270+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:04:25.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:04:25.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:04:25.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.027 seconds
[2024-05-17T03:04:56.147+0000] {processor.py:161} INFO - Started process (PID=17583) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:04:56.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:04:56.148+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:04:56.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:04:56.155+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:04:56.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:04:56.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:04:56.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.022 seconds
[2024-05-17T03:05:27.010+0000] {processor.py:161} INFO - Started process (PID=17634) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:05:27.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:05:27.012+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:05:27.011+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:05:27.016+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:05:27.015+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:05:27.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:05:27.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T03:05:57.903+0000] {processor.py:161} INFO - Started process (PID=17691) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:05:57.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:05:57.905+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:05:57.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:05:57.908+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:05:57.908+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:05:57.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:05:57.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:06:28.787+0000] {processor.py:161} INFO - Started process (PID=17748) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:06:28.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:06:28.789+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:06:28.789+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:06:28.792+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:06:28.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:06:28.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:06:28.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:06:59.612+0000] {processor.py:161} INFO - Started process (PID=17799) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:06:59.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:06:59.613+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:06:59.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:06:59.617+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:06:59.616+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:06:59.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:06:59.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:07:30.478+0000] {processor.py:161} INFO - Started process (PID=17850) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:07:30.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:07:30.479+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:07:30.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:07:30.483+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:07:30.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:07:30.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:07:30.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:08:01.338+0000] {processor.py:161} INFO - Started process (PID=17905) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:08:01.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:08:01.339+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:08:01.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:08:01.346+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:08:01.345+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:08:01.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:08:01.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.023 seconds
[2024-05-17T03:08:32.218+0000] {processor.py:161} INFO - Started process (PID=17958) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:08:32.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:08:32.219+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:08:32.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:08:32.223+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:08:32.222+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:08:32.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:08:32.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:09:03.029+0000] {processor.py:161} INFO - Started process (PID=18009) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:09:03.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:09:03.030+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:09:03.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:09:03.034+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:09:03.033+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:09:03.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:09:03.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:09:33.905+0000] {processor.py:161} INFO - Started process (PID=18060) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:09:33.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:09:33.907+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:09:33.906+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:09:33.910+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:09:33.909+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:09:33.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:09:33.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T03:10:04.830+0000] {processor.py:161} INFO - Started process (PID=18117) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:10:04.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:10:04.832+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:10:04.831+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:10:04.838+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:10:04.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:10:04.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:10:04.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.023 seconds
[2024-05-17T03:10:35.675+0000] {processor.py:161} INFO - Started process (PID=18168) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:10:35.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:10:35.677+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:10:35.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:10:35.681+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:10:35.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:10:35.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:10:35.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:11:06.530+0000] {processor.py:161} INFO - Started process (PID=18219) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:11:06.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:11:06.531+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:11:06.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:11:06.535+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:11:06.535+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:11:06.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:11:06.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.021 seconds
[2024-05-17T03:11:37.411+0000] {processor.py:161} INFO - Started process (PID=18271) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:11:37.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:11:37.412+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:11:37.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:11:37.417+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:11:37.416+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:11:37.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:11:37.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.021 seconds
[2024-05-17T03:12:08.167+0000] {processor.py:161} INFO - Started process (PID=18328) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:12:08.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:12:08.169+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:12:08.168+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:12:08.173+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:12:08.172+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:12:08.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:12:08.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.022 seconds
[2024-05-17T03:12:39.061+0000] {processor.py:161} INFO - Started process (PID=18379) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:12:39.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:12:39.063+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:12:39.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:12:39.066+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:12:39.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:12:39.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:12:39.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T03:13:09.794+0000] {processor.py:161} INFO - Started process (PID=18430) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:13:09.795+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:13:09.796+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:13:09.796+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:13:09.800+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:13:09.799+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:13:09.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:13:09.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
[2024-05-17T03:13:40.586+0000] {processor.py:161} INFO - Started process (PID=18479) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:13:40.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:13:40.587+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:13:40.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:13:40.605+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:13:40.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:13:40.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:13:40.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.033 seconds
[2024-05-17T03:14:11.374+0000] {processor.py:161} INFO - Started process (PID=18537) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:14:11.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:14:11.376+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:14:11.376+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:14:11.380+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:14:11.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:14:11.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:14:11.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.020 seconds
[2024-05-17T03:14:42.158+0000] {processor.py:161} INFO - Started process (PID=18588) to work on /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:14:42.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ingest_bundesliga_match_scores.py for tasks to queue
[2024-05-17T03:14:42.159+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:14:42.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:14:42.163+0000] {logging_mixin.py:188} INFO - [2024-05-17T03:14:42.162+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ingest_bundesliga_match_scores.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_bundesliga_match_scores.py", line 6, in <module>
    from airflow.providers.snowflake.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.transfers.s3_to_snowflake'
[2024-05-17T03:14:42.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_bundesliga_match_scores.py
[2024-05-17T03:14:42.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ingest_bundesliga_match_scores.py took 0.019 seconds
