[2024-05-15T15:00:11.355+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T15:00:11.368+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parsing_recipes.store_data scheduled__2024-05-15T14:58:00+00:00 [queued]>
[2024-05-15T15:00:11.371+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parsing_recipes.store_data scheduled__2024-05-15T14:58:00+00:00 [queued]>
[2024-05-15T15:00:11.372+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-15T15:00:11.377+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_data> on 2024-05-15 14:58:00+00:00
[2024-05-15T15:00:11.381+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11784) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T15:00:11.381+0000] {standard_task_runner.py:63} INFO - Started process 11785 to run task
[2024-05-15T15:00:11.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parsing_recipes', 'store_data', 'scheduled__2024-05-15T14:58:00+00:00', '--job-id', '6321', '--raw', '--subdir', 'DAGS_FOLDER/recipes.py', '--cfg-path', '/tmp/tmp6950gotb']
[2024-05-15T15:00:11.382+0000] {standard_task_runner.py:91} INFO - Job 6321: Subtask store_data
[2024-05-15T15:00:11.404+0000] {task_command.py:426} INFO - Running <TaskInstance: parsing_recipes.store_data scheduled__2024-05-15T14:58:00+00:00 [running]> on host 53697f0c267a
[2024-05-15T15:00:11.443+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parsing_recipes' AIRFLOW_CTX_TASK_ID='store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T14:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-15T14:58:00+00:00'
[2024-05-15T15:00:11.444+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T15:00:11.458+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-15T15:00:11.463+0000] {logging_mixin.py:188} INFO - None
[2024-05-15T15:00:11.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T15:00:11.464+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/recipes.py", line 192, in store_data
    for r in parsed_records:
TypeError: 'NoneType' object is not iterable
[2024-05-15T15:00:11.469+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parsing_recipes, task_id=store_data, run_id=scheduled__2024-05-15T14:58:00+00:00, execution_date=20240515T145800, start_date=20240515T150011, end_date=20240515T150011
[2024-05-15T15:00:11.474+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6321 for task store_data ('NoneType' object is not iterable; 11785)
[2024-05-15T15:00:11.483+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T15:00:11.491+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T15:00:11.492+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
