[2024-05-10T08:55:04.434+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T08:55:04.450+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_push_and_pull_example_dag.pull_from_multiple manual__2024-05-10T08:55:03.497801+00:00 [queued]>
[2024-05-10T08:55:04.455+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_push_and_pull_example_dag.pull_from_multiple manual__2024-05-10T08:55:03.497801+00:00 [queued]>
[2024-05-10T08:55:04.455+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-10T08:55:04.463+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): pull_from_multiple> on 2024-05-10 08:55:03.497801+00:00
[2024-05-10T08:55:04.468+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4986) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T08:55:04.469+0000] {standard_task_runner.py:63} INFO - Started process 4989 to run task
[2024-05-10T08:55:04.468+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xcom_push_and_pull_example_dag', 'pull_from_multiple', 'manual__2024-05-10T08:55:03.497801+00:00', '--job-id', '5843', '--raw', '--subdir', 'DAGS_FOLDER/io_dag.py', '--cfg-path', '/tmp/tmplhoh9kes']
[2024-05-10T08:55:04.470+0000] {standard_task_runner.py:91} INFO - Job 5843: Subtask pull_from_multiple
[2024-05-10T08:55:04.494+0000] {task_command.py:426} INFO - Running <TaskInstance: xcom_push_and_pull_example_dag.pull_from_multiple manual__2024-05-10T08:55:03.497801+00:00 [running]> on host 92f239b8dd4a
[2024-05-10T08:55:04.538+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xcom_push_and_pull_example_dag' AIRFLOW_CTX_TASK_ID='pull_from_multiple' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T08:55:03.497801+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T08:55:03.497801+00:00'
[2024-05-10T08:55:04.539+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T08:55:04.555+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T08:55:04.555+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/io_dag.py", line 23, in pull_from_multiple
    print(value1, value2)
          ^^^^^^
NameError: name 'value1' is not defined. Did you mean: 'values1'?
[2024-05-10T08:55:04.562+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=xcom_push_and_pull_example_dag, task_id=pull_from_multiple, execution_date=20240510T085503, start_date=20240510T085504, end_date=20240510T085504
[2024-05-10T08:55:04.568+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5843 for task pull_from_multiple (name 'value1' is not defined; 4989)
[2024-05-10T08:55:04.607+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T08:55:04.616+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T08:55:04.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
